# Generated by Django 3.0.8 on 2020-08-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='deadline',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
