# Generated by Django 3.0.8 on 2020-08-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0003_quote_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='document',
            field=models.FileField(upload_to='quote/'),
        ),
    ]
