# Generated by Django 3.0.8 on 2020-07-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_photo_main_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
    ]
